"""empty message

Revision ID: da4430a3f8f7
Revises: 
Create Date: 2019-12-11 21:26:44.515376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4430a3f8f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_source_id', sa.Integer(), nullable=True),
    sa.Column('hostIP', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('verb', sa.String(length=8), nullable=True),
    sa.Column('path', sa.String(length=2043), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('hash_code', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_lines_date'), 'log_lines', ['date'], unique=False)
    op.create_index(op.f('ix_log_lines_hash_code'), 'log_lines', ['hash_code'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_index(op.f('ix_log_lines_hash_code'), table_name='log_lines')
    op.drop_index(op.f('ix_log_lines_date'), table_name='log_lines')
    op.drop_table('log_lines')
    op.drop_table('users')
    op.drop_table('log_sources')
    # ### end Alembic commands ###
